# Generated by Django 5.0 on 2023-12-14 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название машины')),
                ('description', models.TextField(blank=True, verbose_name='Дайте описание машины')),
                ('photo', models.ImageField(upload_to='cars/', verbose_name='Добавьте фото')),
                ('cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)], verbose_name='Укажите цену')),
                ('car_url', models.URLField(blank=True, verbose_name='Укажите ссылку на товар')),
                ('type_car', models.CharField(choices=[('Спортивная', 'Спортивная'), ('Олдовая', 'Олдовая'), ('Современная', 'Современная'), ('Классическая', 'Классическая')], max_length=100)),
                ('number_customer', models.CharField(default='+996', max_length=14, verbose_name='Номер продавца')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
