# Generated by Django 5.0 on 2023-12-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='oil',
            field=models.CharField(max_length=100, null=True, verbose_name='Укажите топливо'),
        ),
    ]
