# Generated by Django 3.2.5 on 2024-01-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[(1, 'M'), (2, 'Ж'), (3, 'Предпочитаю не отвечать')], max_length=100, null=True, verbose_name='Ваш пол'),
        ),
    ]
