# Generated by Django 3.2.5 on 2024-01-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'Ж'), ('UNDEFINED', 'Предпочитаю не отвечать')], max_length=100, null=True, verbose_name='Ваш пол'),
        ),
    ]
